# yaml-language-server: $schema=https://blue-build.org/schema.json
name: imu-os
description: Arch-rival of the meta, the ultimate gaming OS for PC.

# ใช้ฐานข้อมูลจาก Fedora Silverblue รุ่นล่าสุด
base-image: ghcr.io/fedora-atomic/silverblue:40
image-version: latest

modules:
  # 1. เปิดใช้งานคลังแสง RPM Fusion เพื่อดึง Driver และ Codec ต่างๆ
  - type: rpm-automation
    repositories:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%(fedora)s.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%(fedora)s.noarch.rpm

  # 2. จัดการเรื่อง Kernel พื้นฐานในเฟสแรก
  - type: blinky-core
    kernel: generic

  # 3. ติดตั้งคลังแอปพลิเคชันและเครื่องมือฝั่ง Gaming (ใช้ rpm-ostree สำหรับฐาน Fedora)
  - type: rpm-ostree
    install:
      - git
      - curl
      - mangohud       # ระบบ HUD เปิดโชว์ FPS/อุณหภูมิ/การทำงานขนาบข้างในเกม
      - gamemode       # ตัวสลับลำดับการทำงานของ CPU/GPU มุ่งเน้นไปที่ตัวเกม
      - openrgb        # เครื่องมือควบคุมไฟ RGB สำหรับเคสและอุปกรณ์พีซี

  # 4. กำหนด Desktop Environment เริ่มต้นให้ผู้ใช้งาน
  - type: default-settings
    desktop: kde       # เลือก KDE Plasma รองรับฟีเจอร์ Wayland, HDR, และ VRR ได้ดีที่สุด